name: Listening Room Scraper

on:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at 10am ET
  workflow_dispatch:      # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Listening Room scraper
        run: python ListeningRoomScrape.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: listening-room-data
          path: listening_room_shows.csv
